version: '3.3'
services:
        Wowza:
                image: mh4nx7net/wowza-perpetual:4.8.0
                container_name: wowza_service
                restart: always
                ports:
                        - "1935:1935"
                        - "8086:8086"
                        - "8087:8087"
                        - "8088:8088"
                volumes:
                        - /srv/docker/wowza/data:/var/lib/wowza
                        - /srv/docker/wowza/log:/var/log/wowza
